[project]
name = 'Existential-Dread-Scheduling-Assistant'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.cosmic-insignificance-perspective-engine]
path = 'contracts/cosmic-insignificance-perspective-engine.clar'
clarity_version = 3
epoch = 'latest'

[contracts.quarter-life-crisis-trigger-scheduler]
path = 'contracts/quarter-life-crisis-trigger-scheduler.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
